### ISSUE TITLE
Problem creating conda environment

### ISSUE THREAD

**Issue by heisersa** [MathiasEskildsen/ONT-AmpSeq#19]
Hello,
I was excited to see the pipeline for analyzing amplicon data, but after following the installation guidelines, I keep running into the issue below when I try to run it. I was wondering whether you had any suggestions for trouble shooting.
Thank you,
Sabrina

(snakemake) sabrinaheiser@Sabrinas-Mac-Studio ONT-AmpSeq-main % snakemake --cores all --use-conda
Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Building DAG of jobs...
Creating conda environment workflow/envs/mapping.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/../envs/mapping.yml:
Command:
mamba env create --quiet --file "/Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/.snakemake/conda/d10a3702117eb3f7d17231a83f84af25_.yaml" --prefix "/Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/.snakemake/conda/d10a3702117eb3f7d17231a83f84af25_"
Output:
error    libmamba Non-conda folder exists at prefix
critical libmamba Aborting.

**Comment by MathiasEskildsen** [comment]
Hi Sabrina,

I’ve run into this issue before, and in my experience, cleaning up all conda environments can sometimes help. You might try removing all conda files with the following command:

rm -rf /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/.snakemake/conda/*

After that, rerun the workflow and see if it resolves the issue.

Let me know how it goes—happy to help troubleshoot further if needed!

Best,
Mathias

**Comment by heisersa** [comment]
Hi Mathias,
thank you for your response - I tried it and it comes up with the same error.
Maybe I am running the wrong lines (I am fairly new to this and am still learning a lot).
I went with the following:

wget -qO- https://github.com/MathiasEskildsen/ONT-AmpSeq/archive/refs/heads/main.tar.gz | tar -xzf -
cd /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main
mamba env create -f environment.yml

Then I adjusted the config file (I had previously run nanoplot.sh successfully and picked the parameters I want).

Next:
snakemake --cores all --use-conda

I also looked into the error messsage more and found this: https://github.com/snakemake/snakemake/issues/3249
So, I installed mamba=1 as they suggested, but I think I am getting a similar error message in addition to another one:

(snakemake) sabrinaheiser@Sabrinas-Mac-Studio ONT-AmpSeq-main % snakemake --cores all --use-conda                                                           

Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Multiple includes of /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/common.smk ignored
Building DAG of jobs...
Creating conda environment workflow/envs/filtering.yml...
Downloading and installing remote packages.
CreateCondaEnvironmentException:
Could not create conda environment from /Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/workflow/rules/../envs/filtering.yml:
Command:
mamba env create --quiet --file "/Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/.snakemake/conda/9915bac838275bd056850d91a47d8fd1_.yaml" --prefix "/Users/sabrinaheiser/Documents/ArcticMetabarcoding/ONT-AmpSeq-main/.snakemake/conda/9915bac838275bd056850d91a47d8fd1_"
Output:
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - chopper=0.7.0*

Current channels:

  - https://conda.anaconda.org/conda-forge
  - https://conda.anaconda.org/bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

I appreciate your help.
Cheers,
Sabrina

**Comment by MathiasEskildsen** [comment]
Hi Sabrina,

No problem. I think there might be a problem with the channels added to your mamba installation. 

Can you try running the following:
mamba search chopper

If no results are coming up, then run:
mamba config --get channels

You should get something along these lines:
--add channels 'bioconda'   # highest priority
--add channels 'conda-forge'
--add channels 'defaults'

If the channel 'bioconda' is not present, then run:
mamba config --add channels bioconda

Then check if chopper can be found by mamba in the added channels:
mamba search chopper

I hope this can solve the issue. However, this might not be the problem as I assume this should be resolved by snakemake&conda, as the channels are specified within each environment file (filtering.yaml, etc.)

If this doesn't resolve the issue, it might be advantageous to start over with a fresh conda installation. 

I'm sorry for the inconvenience. Hopefully we can resolve your issues and get you processing!

Best,
Mathias

**Comment by heisersa** [comment]
Hi Mathias,
thank you for your continued help!
I ended up reinstalling conda, but the problem persists.

I am now wondering whether my system is the problem (osx-arm64).
copper 0.7.0 does not seem to be available for it, so I changed the version in filtering.yml to 0.9.2 (I realize that may create downstream problems if the newer versions interfere with the code, but I thought I would give it a try).

Next time I tried, I ran into an issue with the dependencies in mapping.yml and made these changes:
name: mapping
channels:
  - conda-forge
  - bioconda
dependencies:
  - minimap2=2.28
  - samtools=1.21

And vsearch.yml:
name: vsearch
channels:
  - bioconda
  - conda-forge
dependencies:
  - vsearch=2.28.1

I have now hit a roadblock with ampvis2.yml
From what I can see, the packages that r-ampvis2 requires are not available for osx-arm64.

I have a few questions:
- Do you think that I am actually addressing the issue here or am I following a wrong lead?
- Do I understand correctly that ampvis2 is an R-package to visualize the results and if that is the case, would I not need it until I analyze the OTU table that this code produces? If that is the case, is there a way to not require the ampvis2 environment here? (I have analyzed OTU tables in R before, so once I have the table, I should be ok)
- alternatively, I can set up an environment that emulates the osx-64 architecture if you think that might be the better solution

Thank you,
Sabrina

**Comment by MathiasEskildsen** [comment]
Hi Sabrina,

I do think you are on the right lead - and nice job changing the dependencies to suit your system needs. It did not cross my mind to check on a ARM65 CPU architecture. However, I think I will borrow a colleagues computer in the coming week, to check it out for myself.

Changing the versions of the tools, should not impact the functionality of the pipeline, as far as I can see it.

Strictly speaking, the final output of ONT-AmpSeq is already produced for you at this point (located somewhere along the lines of ONT-AmpSeq-main/results/final/{id}/OTUtable_tax_{id}_{tax}.tsv).

You can use this file to analyze for yourself in R. I would recommend everyone to do this by themselves anyways, as the visualizations done in the pipeline is very limited and only exploratory. 

Best,
Mathias
